results_dir: "???"
model:
  backbone: nvdinov2_vit_large_legacy
  input_width: 224
  input_height: 224 
  feat_dim: 1024
export:
  batch_size: -1
  onnx_file: "???"
  checkpoint: "???"
  opset_version: 17 # required for FAN/NVDINOv2 backbones