results_dir: "???"
model:
  backbone: nvdinov2_vit_large_legacy
  input_width: 224
  input_height: 224 
  feat_dim: 1024
dataset:
  workers: 8
  val_dataset:
    reference: "???"
    query: ""
inference:
  inference_input_type: classification_folder
  input_path: "???"
  batch_size: 16
  
