- hosts: all
  gather_facts: yes
  vars_files:
    - cns_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
    - set_fact:
        cns_docker: "{{ cns_docker }}"
        cns_nvidia_driver: "{{ cns_nvidia_driver }}"
        cns_version: "{{ cns_version }}"
        cns_validation: "{{ cns_validation }}"
        confidential_computing: "{{ confidential_computing }}"

    - name: Checking Nouveau is disabled
      become: true
      shell: "lsmod | grep nouveau"
      register: nouveau_result
      failed_when: false

    - name: unload nouveau
      when: nouveau_result.rc == 0
      become: true
      modprobe:
        name: nouveau
        state: absent
      ignore_errors: true

    - name: blacklist nouveau
      when: nouveau_result.rc == 0
      become: true
      copy:
        dest: "/etc/modprobe.d/blacklist-nouveau.conf"
        owner: "root"
        group: "root"
        mode: "0644"
        content: |
          blacklist nouveau
          options nouveau modeset=0

    - name: check for Kernel SNP release
      shell: uname -r | awk -F'-' '{print $3}'
      register: snp

    - name: conf_compu_snp_install script
      become: true
      when: "confidential_computing == true and snp.stdout != 'snp'"
      copy:
        src: "{{lookup('pipe', 'pwd')}}/files/conf_compu_snp_install.sh"
        dest: "{{ ansible_user_dir }}"
        mode: 0777

    - name: Run conf_compu_snp_install script, please wait
      become: true
      when: "confidential_computing == true and snp.stdout != 'snp'"
      shell: "bash {{ ansible_user_dir }}/conf_compu_snp_install.sh >> {{ ansible_user_dir }}/snp_install.log"

    - name: update-initramfs-ubuntu
      become: true
      command: update-initramfs -u
      when: ansible_os_family == "Debian" and nouveau_result.rc == 0

    - name: update-initramfs-rhel
      become: true
      command: dracut --force
      when: ansible_os_family == "RedHat" and nouveau_result.rc == 0

    - name: Check SELinux Status on RedHat
      when: ansible_distribution == 'RedHat'
      shell: sestatus | grep -i 'Current mode' | awk '{print $3}'
      register: selinuxstatus

    - name: Update SELinux Status on RHEL system
      when: ansible_distribution == 'RedHat' and selinuxstatus.stdout == 'enforcing'
      become: true
      shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

    - name: reboot the system
      when: "nouveau_result.rc == 0 or ansible_os_family == 'RedHat' and selinuxstatus.stdout == 'enforcing' or snp.stdout != 'snp' and confidential_computing == true"
      become: true
      reboot:
        reboot_timeout: 900

    - name: Install PreRequisistes dependencies
      when: ansible_distribution == 'Ubuntu'
      become: true
      apt:
        name: ['mokutil']
        state: present
        update_cache: yes

    - name: Install PreRequisistes dependencies
      when: ansible_distribution == 'RedHat'
      become: true
      yum:
        name: ['mokutil']
        state: present
        update_cache: yes

    - name: Get Speedtest CLI
      get_url:
        url: https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
        dest: /tmp/speedtest-cli
        mode: '0777'

    - name: Check Internet Speed
      ignore_errors: true
      failed_when: false
      shell: /usr/bin/python3 /tmp/speedtest-cli --secure --simple
      register: speed
      async: 30

    - name: Report Valid Internet Speed
      shell: echo {{ speed.stdout_lines[1] }} | awk '{print $3}'
      register: speedtest
      ignore_errors: true
      failed_when: "'Kbit/s' in speedtest.stdout"

    - name: check secure boot
      shell: mokutil --sb-state | awk '{print $2}'
      register: secure_boot
      failed_when: "'enabled' in secure_boot.stdout"
      ignore_errors: true

    - name: check enough storage
      shell: df --block-size 1g / --output=avail | tail -1 | sed "s/ //g"
      register: size
      failed_when: " size.stdout | int <= 40 and ansible_architecture == 'x86_64'"

    - name: Check Number of CPU's
      failed_when: ansible_processor_vcpus < 2
      shell: "echo 'minimum 2 CPUs required'"

    - name: Check memory requirements
      failed_when: ansible_memtotal_mb < 4096
      shell: "echo 'minimum 4GB memory required'"

    - name: Clean up kube config
      become: true
      file:
        path: /root/.kube
        state: absent

    - name: Get Nvidia Tegra Release
      shell: uname -r | awk -F'-' '{print $2}'
      register: release

    - set_fact:
        release: "{{ release.stdout }}"

    - name: Check OS Support x86/ARM systems
      shell: "echo 'Not a Valid Installation please use Ubuntu to 20.04 and retry'"
      when: cns_version <= 6.4
      failed_when: "cns_version <= 6.4 and ansible_distribution_major_version >= '22' and release != 'tegra'"

    - name: Check OS Support x86/ARM systems
      shell: "echo 'Not a Valid Installation please use Ubuntu to 22.04 and retry'"
      when: cns_version >= 7.0
      failed_when: "cns_version >= 7.0 and ansible_distribution_major_version <= '20' and release != 'tegra'"

    - name: Check CNS Version support for RHEL
      shell: "echo 'Not a Valid Installation please use CNS Version 10.0 above and retry'"
      failed_when: "cns_version < 10.0 and ansible_distribution in ['RedHat', 'CentOS']"
      
#    - name: Add DHCP Mac to netplan 
#      become: true 
#      args: 
#        warn: false 
#      shell: 'sudo sed -ie "/dhcp4: .*/a\      dhcp-identifier: mac" /etc/netplan/*' 
 
 #   - name: Apply DHCP mac to NetPlan 
 #     become: true 
 #     shell: netplan apply 

- when: "cns_version > 4.1"
  import_playbook: prerequisites.yaml

- when: "cns_docker == true and release != 'tegra'"
  import_playbook: nvidia-docker.yaml

- import_playbook: nvidia-driver.yaml
  when: "cns_nvidia_driver == true and release != 'tegra'"

- when: "cns_version > 4.1"
  import_playbook: k8s-install.yaml

- when: "cns_version > 4.1 and release != 'tegra'"
  import_playbook: operators-install.yaml

- hosts: all
  gather_facts: yes
  vars_files:
    - cns_values.yaml
  tasks:
    - name: Get Nvidia Tegra Release
      shell: uname -r | awk -F'-' '{print $2}'
      register: release

    - set_fact:
        release: "{{ release.stdout }}"

    - name: Reboot the system
      become: true
      when: cns_nvidia_driver == true and use_open_kernel_module == false
      reboot:
        reboot_timeout: 900

    - name: Waiting for Cluster to up and running
      args:
        executable: /bin/bash
      shell: |
        sleep 240
        state=$(kubectl get pods -n nvidia-gpu-operator | egrep -v 'Running|Completed|NAME' | wc -l)
        while [ $state != 0 ]
          do
            sleep 10
            state=$(kubectl get pods -n nvidia-gpu-operator | egrep -v 'Running|Completed|NAME' | wc -l)
          done
      register: status
      when: "cns_version > 4.1 and cns_validation == true and release != 'tegra'"

- when: "cns_version > 4.1 and cns_validation == true and release != 'tegra'"
  import_playbook: cns-validation.yaml