- hosts: master
  vars_files:
    - cns_values.yaml
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  tasks:
   - name: Get Nvidia Tegra Release
     shell: uname -r | awk -F'-' '{print $2}'
     register: release

   - set_fact:
      release: "{{ release.stdout }}"

   - name: Validate whether Kubernetes cluster installed
     shell: kubectl cluster-info
     register: k8sup
     no_log: True
     failed_when: false

   - name: Reset Kubernetes component
     when: "'running' not in k8sup.stdout"
     become: true
     shell: "kubeadm reset --force"
     no_log: True
     failed_when: false

   - name: remove etcd directory
     become: true
     when: "'running' not in k8sup.stdout"
     file:
       path: "/var/lib/etcd"
       state: absent

   - name: Check proxy conf exists
     when: proxy == true
     lineinfile:
       path: /etc/environment
       regexp: '^http_proxy=*'
       state: absent
     check_mode: yes
     changed_when: false
     register: proxyconf

   - name: Get Host IP
     shell: interface=$(ip a | grep 'state UP' |  egrep 'enp*|ens*|eno*|enc*|eth*|bond*|wlan*' | awk '{print $2}' | sed 's/://g'); for i in $interface; do ifconfig $i | grep -iw inet | awk '{print $2}'; done
     register: network

   - name: subnet information
     shell: "echo {{ network.stdout_lines[0] }} | cut -d. -f1-3"
     register: subnet

   - name: add proxy lines to environment
     when: proxy == true and not proxyconf.found
     become: true
     lineinfile:
       dest: /etc/environment
       insertafter: "PATH="
       line: "{{ item }}"
     loop:
       - http_proxy={{ http_proxy }}
       - HTTP_PROXY={{ http_proxy }}
       - https_proxy={{ https_proxy }}
       - HTTPS_PROXY={{ https_proxy }}
       - no_proxy={{ network.stdout_lines[0] }},localhost,127.0.0.0/8,10.96.0.1/24,10.244.0.0/16,192.168.32.0/22,{{ subnet.stdout }}.0/24
       - NO_PROXY={{ network.stdout_lines[0] }},localhost,127.0.0.0/8,10.96.0.1/24,10.244.0.0/16,192.168.32.0/22,{{ subnet.stdout }}.0/24

   - name: source the env
     when: proxy == true and not proxyconf.found
     shell: source /etc/environment
     args:
       executable: /bin/bash

   - name: check default gateway
     shell: ip r | grep default
     failed_when: false
     register: gateway
     when: proxy == true

   - name: add default gateway
     shell: route add -net 0.0.0.0/0 gw {{ network.stdout_lines[0] }}
     when: gateway.rc | default ('') == 1 and proxy == true

   - name: Initialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'containerd' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'containerd' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'containerd' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and containerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'containerd' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-O for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'cri-o' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:///var/run/crio/crio.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-O for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'cri-o' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:///var/run/crio/crio.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-O for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'cri-o' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/crio/crio.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-O for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'cri-o' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///var/run/crio/crio.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-Dockerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'cri-dockerd' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:///run/cri-dockerd.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-Dockerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'cri-dockerd' and release != 'tegra'"
     command: 'kubeadm init --pod-network-cidr=192.168.32.0/22 --cri-socket=unix:///run/cri-dockerd.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-Dockerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == false and container_runtime == 'cri-dockerd' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///run/cri-dockerd.sock --kubernetes-version="v{{ k8s_version }}" --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Initialize the Kubernetes cluster using kubeadm and CRI-Dockerd for Cloud Native Stack
     when: "'running' not in k8sup.stdout and proxy == true and container_runtime == 'cri-dockerd' and release == 'tegra'"
     command: 'kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=unix:///run/cri-dockerd.sock --kubernetes-version="v{{ k8s_version }}" --apiserver-advertise-address={{ network.stdout_lines[0] }} --image-repository={{ k8s_registry }}'
     become: true
     register: kubeadm

   - name: Create kube directory
     when: "'running' not in k8sup.stdout"
     file:
      path: $HOME/.kube
      state: directory

   - name: admin permissions
     when: "'running' not in k8sup.stdout"
     become: true
     file:
       path: /etc/kubernetes/admin.conf
       mode: '0644'

   - name: Copy kubeconfig to home
     when: "'running' not in k8sup.stdout"
     copy:
       remote_src: yes
       src:  /etc/kubernetes/admin.conf
       dest:  $HOME/.kube/config
       mode: '0600'

   - pause:
       seconds: 15
     when: "'running' not in k8sup.stdout"

   - name: Install networking plugin to Kubernetes cluster on NVIDIA Cloud Native Stack
     when: "'running' not in k8sup.stdout and cns_version >= 7.1 and release != 'tegra' or cns_version == 6.4 and release != 'tegra'"
     command: "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/calico.yaml"

   - name: Install networking plugin to Kubernetes cluster on NVIDIA Cloud Native Stack
     when: "cns_version <= 6.3 and ansible_distribution_major_version == '20' and release != 'tegra' or cns_version == 7.0 and release != 'tegra' and ansible_distribution_major_version == '22'"
     command: "kubectl apply -f https://projectcalico.docs.tigera.io/archive/v{{ calico_version }}/manifests/calico.yaml"

   - name: Update Network plugin for Calico on NVIDIA Cloud Native Stack
     when: "'running' not in k8sup.stdout and cns_version >= 3.1 and release != 'tegra'"
     shell: "sleep 5; kubectl set env daemonset/calico-node -n kube-system IP_AUTODETECTION_METHOD=interface=ens*,eth*,enc*,bond*,enp*,eno*"

   - name: Install networking plugin to Kubernetes cluster on NVIDIA Cloud Native Stack
     when: "'running' not in k8sup.stdout and release == 'tegra'"
     command: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v{{ flannel_version }}/Documentation/kube-flannel.yml"

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cns_version < 7.0"
     failed_when: false
     command: kubectl taint nodes --all node-role.kubernetes.io/master-

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cns_version == 7.0 or 'running' not in k8sup.stdout and cns_version == 7.1 or 'running' not in k8sup.stdout and cns_version == 7.2 or 'running' not in k8sup.stdout and cns_version == 7.3 or 'running' not in k8sup.stdout and cns_version == 7.4 or 'running' not in k8sup.stdout and cns_version == 7.5"
     command: kubectl taint nodes --all node-role.kubernetes.io/master- node-role.kubernetes.io/control-plane-

   - name: Taint the Kubernetes Control Plane node
     when: "'running' not in k8sup.stdout and cns_version >= 8.0 or 'running' not in k8sup.stdout and cns_version == 6.4"
     failed_when: false
     command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

   - name: Generate join token
     become: true
     when: "'running' not in k8sup.stdout"
     shell: kubeadm token create --print-join-command
     register: kubeadm_join_cmd

   - set_fact:
       kubeadm_join: "{{ kubeadm_join_cmd.stdout }}"
     when: "'running' not in k8sup.stdout"

   - name: Store join command
     when: "'running' not in k8sup.stdout"
     become: true
     copy:
       content: "{{ kubeadm_join }}"
       dest: "/tmp/kubeadm-join.command"

   - name: Copy Join Command
     when: "'running' not in k8sup.stdout"
     fetch:
       src: "/tmp/kubeadm-join.command"
       dest: "/tmp/kubeadm-join.command"
       flat: true

   - name: Store Kubernetes cluster status
     when: "'running' not in k8sup.stdout"
     become: true
     copy:
       content: "{{ k8sup.stdout }}"
       dest: "/tmp/k8sup.status"

   - name: Copy k8s status
     when: "'running' not in k8sup.stdout"
     fetch:
       src: "/tmp/k8sup.status"
       dest: "/tmp/k8sup.status"
       flat: true

- hosts: nodes
  vars_files:
    - cns_values.yaml
  tasks:
   - name: Copy Kubernetes cluster status
     become: true
     copy:
       src: "/tmp/k8sup.status"
       dest: "/tmp/k8sup.status"

   - name: Search for Kubernetes status
     become: true
     register: k8sup
     shell: "cat /tmp/k8sup.status"

   - name: Reset Kubernetes component
     become: true
     shell: "kubeadm reset --force"
     register: reset_cluster
     failed_when: false
     when: "'running' not in k8sup.stdout"

   - name: Create kube directory
     become: true
     file:
       path: /etc/kubernetes
       state: directory

   - name: Copy kubeadm-join command to node
     become: true
     copy:
       src: "/tmp/kubeadm-join.command"
       dest: "/tmp/kubeadm-join.command"

   - name: Get the Active Mellanox NIC on nodes
     when: "enable_network_operator == true and cns_version >= 4.1"
     become: true
     shell: "for device in `sudo lshw -class network -short | grep -i ConnectX | awk '{print $2}' | egrep -v 'Device|path' | sed '/^$/d'`;do echo -n $device; sudo ethtool $device | grep -i 'Link detected'; done | grep yes | awk '{print $1}' > /tmp/$(hostname)-nic"
     register: node_nic

   - name: Copy Mellanox NIC Active File to master
     when: "enable_network_operator == true and cns_version >= 4.1"
     become: true
     fetch:
       src: "/tmp/{{ ansible_nodename }}-nic"
       dest: "/tmp/"
       flat: yes

- hosts: nodes
  vars:
     kubeadm_join: "{{ lookup('file', '/tmp/kubeadm-join.command') }}"
  tasks:

   - name: Search for Kubernetes status
     become: true
     register: k8sup
     shell: "cat /tmp/k8sup.status"

   - name: Run kubeadm join
     become: true
     shell: "{{ kubeadm_join }}"
     when: "'running' not in k8sup.stdout"

   - pause:
       seconds: 30
     when: "'running' not in k8sup.stdout"