dataset:
  data:
    samples_per_gpu: 128
    workers_per_gpu: 8
    train:
      data_prefix: /data/imagenet/train
      pipeline: # Augmentations alone
        - type: RandomResizedCrop
          scale: 224
        - type: RandomFlip
          prob: 0.5
          direction: "horizontal"
        - type: ColorJitter
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
    val:
      data_prefix: /data/imagenet/val
    test:
      data_prefix: /data/imagenet/val

model:
  backbone:
    type: "open_clip"
    custom_args:
      model_name: "ViT-B-32"
    freeze: true
    pretrained: laion2b_s34b_b79k
  head:
    type: TAOLinearClsHead
    num_classes: 1000
    in_channels: 512
    loss:
      type: CrossEntropyLoss
      loss_weight: 1.0
      use_soft: False
    topk: [1, 5]

train:
  train_config:
    find_unused_parameters: True
    optimizer:
      type: AdamW
      lr: 1e-3
    lr_config:
      type: CosineAnnealingLR
      T_max: 200
      by_epoch: True
      begin: 0
    optimizer_config:
      grad_clip:
        max_norm: 5.0
    runner:
      max_epochs: 10
    checkpoint_config:
      interval: 1
    logging:
      interval: 50
    validate: True
    evaluation:
      interval: 1
